### ISSUE TITLE
error while connecting to virus total

### ISSUE THREAD

**Issue by mvarunsai** [alexandreborges/malwoverview#22]
i have trying to run the tool one a example url and also try to get a report from a while but "Error While connecting to Viru Total" error is thrown

**Comment by secraven** [comment]
Taking a guess here.  Are you sure you entered your API key correctly in the .malwapi.conf file?

**Comment by mvarunsai** [comment]
> Taking a guess here. Are you sure you entered your API key correctly in the .malwapi.conf file?

@secraven  No i have given it right...when i hardcoded the code and added the api keys directly into the code..it was working.. can you tell me where should the .malwapi.conf file be present to read it. In windows system the home directory is the windows directory so i placed the file there. But now im having second thoughts.

**Comment by alexandreborges** [comment]
Mvarunsai, good morning. 

Please, check whether:

1. You really have the correct .malwapi.conf in your home directory (ex: /home/aborges/.malwapi.conf)
2. You've entered APIs in a right way (without quotes)

I'm inserting an output below using -u option: 

![image](https://user-images.githubusercontent.com/13165245/97527930-43963c80-198b-11eb-985c-3ada83aeb42b.png)

Anyway, in few weeks I'll publish a new version of Malwoverview which will introduce new endpoints AND update several functions (I can't do it right now because I'm really busy...) 

Please, let me know if you're still facing problems. 

Have an excellent day.

Alexandre.

**Comment by alexandreborges** [comment]
Mvarunsai, 

Good morning. I'm closing the thread.

Have an excellent day.

Alexandre.
