### ISSUE TITLE
Malwoverview commands on memory dump files.

### ISSUE THREAD

**Issue by Atharva-Marathe** [alexandreborges/malwoverview#26]
While trying to execute malwoverview command on memorydump i.e .mem files the command to export to virus total doesnt seems to work.
Is there a way out such that the processes in  a memory dump could be analyzed and exported to virus total or malshare?
![malwoverview1](https://user-images.githubusercontent.com/43780522/116874252-a4524a80-ac36-11eb-93a6-7f683cdbcca7.PNG)
![malwoverview2](https://user-images.githubusercontent.com/43780522/116874270-ab795880-ac36-11eb-8f80-b53d713eaaa8.PNG)

**Comment by alexandreborges** [comment]
Atharva-Marathe, 

Good afternoon. 

Options from Malwoverview are not focused on memory images, but only on PE Format files, ELF and so on. I'm planning to write a plugin for Volatility to interact with Malwoverview and perform exactly these steps you've mentioned in the message. For now, the issue is my short time, but I'll try to reserve some time to do it.

Have an excellent day.
