### ISSUE TITLE
Virus total connection issue

### ISSUE THREAD

**Issue by teto2005** [alexandreborges/malwoverview#27]
running the cmd with both arg -u or -r returns back with error message "Error while connecting to Virus Total!" given that I am using Notebook terminal.
<img width="840" alt="aaa" src="https://user-images.githubusercontent.com/10776616/124022695-6f236800-d9ed-11eb-8a82-38b2060746c9.png">

**Comment by alexandreborges** [comment]
Neil,

Good evening. How are you?

Please, check your connection because both commands are working perfectly:

![image](https://user-images.githubusercontent.com/13165245/124043900-7bee8e80-d9e2-11eb-91b1-4bb7a185382b.png)

![image](https://user-images.githubusercontent.com/13165245/124044002-bd7f3980-d9e2-11eb-8b20-0b174aeefdf0.png)

Please, let me know further details about your issue. 

Have an excellent day and stay safe.

Alexandre.

**Comment by teto2005** [comment]
Alex, 
Thanks am fine. How are you?
I checked it again and my connection is ok still the same issues. Do I have to config it some how?
Thanks :)

**Comment by alexandreborges** [comment]
Neil, 

Good morning. How are you?

I'm fine. The only necessary configuration is creating the .malwapi.conf file with all APIs under the HOME DIRECTORY. For example: /root/.malwapi.conf. 

Please, check if:

1. You're using Python 3.8 or  newer.
2. All packages have been successfully installed.
3. All necessary APIs are registered inside the .malwapi.conf file.

I've been using Kali Linux and Ubuntu for running Malwoverview. 

Have an excellent Friday.

Alex.
