### ISSUE TITLE
Threatcrowd API is not working 

### ISSUE THREAD

**Issue by BartoszJelen** [alexandreborges/malwoverview#34]
Threatcrowd can not connect anymore. Is this because they are Alien vaults now? Will there be a fix for this? 
Polyswarm also seems to have problem with the connection

**Comment by alexandreborges** [comment]
Dear BartoszJelen, 

Good evening. How are you?

Yes, it seems that ThreatCrowd  is facing some instability and sometimes I receives a return, but sometimes I don't. Anyway, I'll release a new and intermediate version soon. I'll include some fixes into other functions and I'm also going to remove it because there're other more relevant endpoints this time.  After this intermediate version I'll release new versions including new endpoints. 

About the Polyswarm, it's OK for me here and I've tested all of its options (please, check attached image). 

Thank you for your feedback and, probably, you'll heard about the new version in the next couple of weeks.

Have an excellent Sunday.

Alexandre.

![image](https://user-images.githubusercontent.com/13165245/173210675-9e09bea1-b2ba-4de8-a8b6-a18fd17386c3.png)
